### ISSUE TITLE
Deploying Node.js and Connecting the Code

### ISSUE THREAD

**Issue by bodbol** [CiscoDevNet/socialminer-sample-code#18]
I have installed the node.js and all the dependencies but when i try to connect the app, i am getting an error
Looking through your instructions, here is the section i am having issues with:

    Change directory to <zipDirectory>/customer-chat/.
    <zipDirectory> is the directory in which the sample was extracted.

When i try this, i am getting the error below:

C:\inetpub>node app.js --socialminer onl-ccxsminer.twoqlab.com
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module 'C:\inetpub\app.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:785:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)[39m
[90m    at internal/main/run_main_module.js:16:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by bodbol** [comment]
If i run it from the inside of the file that was zipped, i get this other error

C:\inetpub\customer-chat>node app.js --socialminer onl-ccxsminer.twoqlab.com
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- C:\inetpub\customer-chat\app.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:785:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:956:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\inetpub\customer-chat\app.js:1:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:914:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:822:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'C:\\inetpub\\customer-chat\\app.js'[39m ]

**Comment by amirkhanjz** [comment]
> I have installed the node.js and all the dependencies but when i try to connect the app, i am getting an error
> Looking through your instructions, here is the section i am having issues with:
> 
> ```
> Change directory to <zipDirectory>/customer-chat/.
> <zipDirectory> is the directory in which the sample was extracted.
> ```
> 
> When i try this, i am getting the error below:
> 
> C:\inetpub>node app.js --socialminer onl-ccxsminer.twoqlab.com
> internal/modules/cjs/loader.js:895
> throw err;
> ^
> 
> Error: Cannot find module 'C:\inetpub\app.js'
> �[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)�[39m
> �[90m at Function.Module._load (internal/modules/cjs/loader.js:785:27)�[39m
> �[90m at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)�[39m
> �[90m at internal/main/run_main_module.js:16:11�[39m {
> code: �[32m'MODULE_NOT_FOUND'�[39m,
> requireStack: []
> }

Open the folder "customer-chat" (where you can see a file named app.js there)
Copy path and open vs code or any npm console 
(Make sure that you have installed npm.js)
If you are using vs code, click on open folder from navigation and paste the clipboard (path) and hit enter
Then open node terminal
If you are using node console or non, simply type cd (path you copied before) then hit the enter

In both ways, now I it's time to type
Npm install
And enter

Then type 
Node app.js --socialminer (your socialminer address)
And then you will be notified about url Wich will open the gate
